set(CPACK_PACKAGE_NAME "rtl-sdr")
set(CPACK_DEBIAN_PACKAGE_NAME "librtlsdr")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_VERSION ${VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Software defined radio receiver for Realtek RTL2832U")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Experimental R820T/R820T2 rtl-sdr tuner driver that tunes down to 13 MHz or lower.
(From my experiments up to 3.4 MHz on R820T2)\n
This package contains the binaries, shared and dev library.") 

set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Mr-Precise/rtl-sdr")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Precise")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")

set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/Generated_Packages")

# set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/COPYING")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

# set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/shlibs;" )

include(CPack)
